-- 코드를 입력하세요
# SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID , SALES_AMOUNT
# FROM ONLINE_SALE
# WHERE DATE_FORMAT(SALES_DATE, '%m') = '03' ORDER BY SALES_DATE ASC

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d'),PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM ONLINE_SALE 
WHERE MONTH(SALES_DATE)=3 
UNION ALL
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d'),PRODUCT_ID,NULL,SALES_AMOUNT
FROM OFFLINE_SALE 
WHERE MONTH(SALES_DATE)=3 
ORDER BY 1,2,3