-- 코드를 입력하세요

SELECT RI.REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS,
ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS RI
RIGHT JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC

# select *
# FROM REST_INFO AS RI
# LEFT JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID

# SELECT * 
# FROM REST_REVIEW 
# WHERE REST_ID = 00004