-- 코드를 입력하세요
# SELECT COUNT(A.MCDP_CD)
SELECT A.MCDP_CD AS 진료과코드, COUNT(A.MCDP_CD) AS 5월예약건수
FROM APPOINTMENT AS A
WHERE DATE_FORMAT(A.APNT_YMD, '%Y-%m') = '2022-05'
GROUP BY A.MCDP_CD
ORDER BY 5월예약건수, 진료과코드