-- 코드를 작성해주세요
-- & 연산으로 비트값 가져오기
SELECT
    ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM
    DEVELOPERS
WHERE
    (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python'))
    OR (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#'))
ORDER BY
    ID;
  
  
  