SELECT SUM(HG.SCORE) AS SCORE, HG.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_GRADE HG
JOIN HR_EMPLOYEES HE ON HG.EMP_NO = HE.EMP_NO
WHERE HG.YEAR = 2022
GROUP BY HG.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
ORDER BY SCORE DESC
LIMIT 1;
